"""initial

Revision ID: 81d91831d0e7
Revises: 
Create Date: 2026-10-01 08:48:15.608337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d91831d0e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_time', sa.Time(), nullable=False),
    sa.Column('notifications_paused_until', sa.Date(), nullable=True),
    sa.Column('bot_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('households',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_households_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_ai_usage_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage')),
    sa.UniqueConstraint('household_id', 'local_date', name='uq_ai_usage_household_date')
    )
    op.create_table('chore_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending_acceptance', 'active', 'archived', name='chore_status'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_chore_templates_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_chore_templates_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_chore_templates_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chore_templates'))
    )
    op.create_index('ix_chore_templates_household_id', 'chore_templates', ['household_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_events_household_id_households'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    op.create_index('ix_events_household_created', 'events', ['household_id', 'created_at'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_invitations_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_invitations_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.id'], name=op.f('fk_invitations_redeemed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_index('ix_invitations_token_hash', 'invitations', ['token_hash'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_memberships_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_memberships_household_user'),
    sa.UniqueConstraint('user_id', name='uq_memberships_user_id')
    )
    op.create_index('ix_memberships_household_id', 'memberships', ['household_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('daily_summary', name='notification_type'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'skipped', name='notification_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_notifications_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('unique_key', name='uq_notifications_unique_key')
    )
    op.create_index('ix_notifications_status_scheduled', 'notifications', ['status', 'scheduled_for'], unique=False)
    op.create_table('task_occurrences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'completed', 'cancelled', name='occurrence_status'), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_task_occurrences_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], name=op.f('fk_task_occurrences_completed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['chore_templates.id'], name=op.f('fk_task_occurrences_template_id_chore_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_occurrences'))
    )
    op.create_index('ix_task_occurrences_assignee_due', 'task_occurrences', ['assignee_user_id', 'due_date'], unique=False)
    op.create_index('ix_task_occurrences_template_id', 'task_occurrences', ['template_id'], unique=False)
    op.create_index('uq_task_occurrences_one_open', 'task_occurrences', ['template_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('assignment_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_type', sa.Enum('chore_assignment', 'task_transfer', name='offer_type'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_id', sa.Integer(), nullable=True),
    sa.Column('initiator_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'expired', 'cancelled', name='offer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], name=op.f('fk_assignment_offers_initiator_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['task_occurrences.id'], name=op.f('fk_assignment_offers_occurrence_id_task_occurrences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_assignment_offers_recipient_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['chore_templates.id'], name=op.f('fk_assignment_offers_template_id_chore_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_offers'))
    )
    op.create_index('ix_assignment_offers_recipient', 'assignment_offers', ['recipient_user_id', 'status'], unique=False)
    op.create_index('uq_assignment_offers_one_pending_occurrence', 'assignment_offers', ['occurrence_id'], unique=True, postgresql_where=sa.text("status = 'pending' AND offer_type = 'task_transfer' AND occurrence_id IS NOT NULL"))
    op.create_index('uq_assignment_offers_one_pending_template', 'assignment_offers', ['template_id'], unique=True, postgresql_where=sa.text("status = 'pending' AND offer_type = 'chore_assignment' AND template_id IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_assignment_offers_one_pending_template', table_name='assignment_offers', postgresql_where=sa.text("status = 'pending' AND offer_type = 'chore_assignment' AND template_id IS NOT NULL"))
    op.drop_index('uq_assignment_offers_one_pending_occurrence', table_name='assignment_offers', postgresql_where=sa.text("status = 'pending' AND offer_type = 'task_transfer' AND occurrence_id IS NOT NULL"))
    op.drop_index('ix_assignment_offers_recipient', table_name='assignment_offers')
    op.drop_table('assignment_offers')
    op.drop_index('uq_task_occurrences_one_open', table_name='task_occurrences', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_task_occurrences_template_id', table_name='task_occurrences')
    op.drop_index('ix_task_occurrences_assignee_due', table_name='task_occurrences')
    op.drop_table('task_occurrences')
    op.drop_index('ix_notifications_status_scheduled', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_memberships_household_id', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_invitations_token_hash', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_events_household_created', table_name='events')
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_chore_templates_household_id', table_name='chore_templates')
    op.drop_table('chore_templates')
    op.drop_table('ai_usage')
    op.drop_table('households')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
